default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  reaping_frequency: 10

development:
  <<: *default
  database: daily_songs_development

test:
  <<: *default
  database: daily_songs_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  statement_limit: 256
